spring.application.name=doceria

# Configurações do Servidor
server.port=8085

# Configurações do Banco de Dados H2 (Em memória)
spring.datasource.url=jdbc:h2:mem:doceriadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Inicialização do Banco (Cria as tabelas automaticamente com base no Product.java)
spring.jpa.hibernate.ddl-auto=update

# Ativa o painel visual do banco de dados no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Desativa o cache do Thymeleaf para que alterações no HTML atualizem mais rápido no desenvolvimento
spring.thymeleaf.cache=false

# Mapeamento para o Spring Boot encontrar as imagens locais na pasta static
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
